{% set name = "fast-histogram" %}
{% set version = "0.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 390973b98af22bda85c29dcf6f008ba0d626321e9bd3f5a9d7a43e5690ea69ea

build:
  skip: true  # [py38]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - pip
    - setuptools-scm
    - wheel
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - fast_histogram
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/astrofrog/fast-histogram
  summary: Fast simple 1D and 2D histograms
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - astrofrog
