{% set name = "fast-histogram" %}
{% set version = "0.9" %}
{% set sha256 = "6325ce42060bb9d1987a3aefffcac45bdd3810bc58ce69716132e23aa49f7a9f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - fast_histogram

about:
  home: http://github.com/astrofrog/fast-histogram
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: Fast 1D and 2D histogram functions in Python
  description: Fast 1D and 2D histogram functions in Python
  doc_url: http://github.com/astrofrog/fast-histogram
  dev_url: http://github.com/astrofrog/fast-histogram

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
