{% set name = "fast-histogram" %}
{% set version = "0.5" %}
{% set sha256 = "0e3849e244909aa68e58305ed101c19c8576176eaf90fd5d79215d5ade51a6a7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - toolchain
    - numpy 1.10.*  # [not (win and (py35 or py36))]
    - numpy 1.11.*  # [win and (py35 or py36)]
  run:
    - python
    - numpy >=1.10  # [not (win and (py35 or py36))]
    - numpy >=1.11  # [win and (py35 or py36)]

test:
  imports:
    - fast_histogram

about:
  home: http://github.com/astrofrog/fast-histogram
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: 'Fast 1D and 2D histogram functions in Python'
  description: Fast 1D and 2D histogram functions in Python
  doc_url: http://github.com/astrofrog/fast-histogram
  dev_url: http://github.com/astrofrog/fast-histogram

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
