{% set name = "fast-histogram" %}
{% set author = "astrofrog" %}
{% set version = "0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ author }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5b8fdedbedc8ab21b2d1a6656a99ef565d6abb4e7cb05c83c1feff184e64e106

build:
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - pip
    - setuptools-scm
    - wheel
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - fast_histogram
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/astrofrog/fast-histogram
  summary: Fast simple 1D and 2D histograms
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - astrofrog
