{% set name = "fast-histogram" %}
{% set version = "0.8" %}
{% set sha256 = "cd55aea64fceee562b3aaaed6c9a15093243d071c5ded23f1ff29c895ad14319" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - fast_histogram

about:
  home: http://github.com/astrofrog/fast-histogram
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: 'Fast 1D and 2D histogram functions in Python'
  description: Fast 1D and 2D histogram functions in Python
  doc_url: http://github.com/astrofrog/fast-histogram
  dev_url: http://github.com/astrofrog/fast-histogram

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
