appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: CAuh70U6fcvQIhpsHKFNUiJ/dGSEH4glMn0Lp3CEqzA1xxR70n1ruQvUoCNuoHOmC1FExxX58xibfklcc58XiNmvtfTbNxdUukkwuxbqIgXruZPX0ndru+xXOShbfvuWcMHrR4rWLI1dmAGVJsiff7S8I+F0dVXsVOBGpJn9nl+PyXoTfFXiUCtmPsqJW7WB1R3casXIui/ET6tFEl1cCVE3K7HrLvI25k62QLYwL5JppV803vSiNotSdOIspCrU+kdFWZgTsq45ZOOcOKDaYZqiKPYYmROX2jAdWEzjichu6MrGokFwTHH+skfs/zJIqoGdBCydk2FyXD2lYR43PZn9TYL+ChdWVUod1Uq8rj5rZWKPIXY3qceDp4DKwXZvwnKHy2bwgdm89rnSfC97q9xcIn3CvxJkBBresrvXZDD7I3QvPoLEPLUT6DAwi6e7ii/vGLZvfzZG19e86DxZicKiogKdMpOA10Ls28Zmawqbag8sPXFOVqrV3A6POa6twfnzMxnqB/+wSgeDow0v/X/qxf7WW93kVzKJY+yOrM4pnAqHBiw9nUnQe149bSa4bjUkySXxVmW2HnW9qCWzsByE6/wrKX6AwLaqtJVKMXDdQqQr9e+5ZU5kE9m30FfdZ6EwMJ1SjvRK6QqJtkw/hhPlNbbkEWjwsif+0nUU34E=}
provider:
  win: azure
